### ISSUE TITLE
Multi programming language should be included

### ISSUE THREAD

**Issue by jzndd** [heyzbw/CSU_Thesis_Template#1]
在实例中，仅仅添加了引入python的高亮语法，可以在模板中添加更多实例，以及建议对引入格式进行 \lstset{} 的宏定义，博文可以看着改改，或者等我忙完了考虑来提一个pr

**Comment by heyzbw** [comment]
感谢提问，欢迎PR，关于python的附录格式的问题，项目参考引入了[python-latex-highlighting](https://github.com/olivierverdier/python-latex-highlighting)项目中的[pythonhighlight.sty](https://github.com/olivierverdier/python-latex-highlighting/blob/master/pythonhighlight.sty)作为格式参考，不过如果想用\lstset{}自定义格式也可以参考附录中关于Matlab格式定义的写法。
